"""
PDF Report Generator Module
Generates professional PDF reports of analysis results
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any, List
import io

from ..matching.hybrid_scorer import MatchResult

class PDFReport(FPDF):
    """Custom PDF class with header and footer"""
    
    def header(self):
        # Logo/Brand
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(79, 70, 229)  # Brand Indigo
        self.cell(0, 10, 'ResuLens AI', 0, 1, 'L')
        
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 116, 139)  # Slate 500
        self.cell(0, 5, 'Intelligent Role Matching Report', 0, 1, 'L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Generated by ResuLens AI on {datetime.now().strftime("%Y-%m-%d %H:%M")} - Page ' + str(self.page_no()), 0, 0, 'C')

class ReportGenerator:
    """Handles report generation logic"""
    
    def __init__(self):
        self.pdf = PDFReport()
        
    def _clean_text(self, text: str) -> str:
        """Remove non-ASCII characters to prevent font errors"""
        if not isinstance(text, str):
            text = str(text)
        # Encode to latin-1 (standard PDF font encoding) and ignore errors, then decode back
        return text.encode('latin-1', 'ignore').decode('latin-1').strip()
        
    def generate(self, result: MatchResult, job_title: str = "Unknown Role") -> bytes:
        """
        Generate PDF report from match results
        
        Args:
            result: MatchResult object
            job_title: Target job title
            
        Returns:
            PDF file bytes
        """
        self.pdf.add_page()
        self.pdf.set_auto_page_break(auto=True, margin=15)
        
        # 1. Executive Summary
        self.pdf.set_font('Helvetica', 'B', 16)
        self.pdf.set_text_color(30, 41, 59)
        self.pdf.cell(0, 10, 'Executive Summary', 0, 1)
        
        self.pdf.set_font('Helvetica', '', 11)
        self.pdf.set_text_color(51, 65, 85)
        self.pdf.multi_cell(0, 7, f"Analysis for position: {self._clean_text(job_title)}")
        self.pdf.ln(5)
        
        # Score Cards (Simulated with cells)
        self._render_score_cards(result)
        self.pdf.ln(10)
        
        # 2. Detailed Breakdown
        self.pdf.set_font('Helvetica', 'B', 14)
        self.pdf.set_text_color(30, 41, 59)
        self.pdf.cell(0, 10, 'Detailed Breakdown', 0, 1)
        
        self._render_metrics_table(result)
        self.pdf.ln(10)
        
        # 3. Skills Analysis
        self.pdf.set_font('Helvetica', 'B', 14)
        self.pdf.cell(0, 10, 'Skills Gap Analysis', 0, 1)
        self._render_skills_analysis(result)
        self.pdf.ln(10)
        
        # 4. Action Plan
        self.pdf.add_page()
        self.pdf.set_font('Helvetica', 'B', 14)
        self.pdf.cell(0, 10, 'Strategic Action Plan', 0, 1)
        self._render_action_plan(result.recommendations)
        
        return bytes(self.pdf.output(dest='S'))
    
    def _render_score_cards(self, result: MatchResult):
        """Render the main score dashboard"""
        # Overall Score Box
        self.pdf.set_fill_color(248, 250, 252)
        self.pdf.rect(10, 55, 190, 30, 'F')
        
        self.pdf.set_xy(15, 60)
        self.pdf.set_font('Helvetica', 'B', 12)
        self.pdf.set_text_color(100, 116, 139)
        self.pdf.cell(50, 10, 'OVERALL MATCH', 0, 0)
        
        self.pdf.set_xy(15, 70)
        self.pdf.set_font('Helvetica', 'B', 24)
        color = self._get_score_color(result.overall_score)
        self.pdf.set_text_color(*color)
        self.pdf.cell(50, 10, f"{result.overall_score}%", 0, 0)
        
        self.pdf.set_xy(70, 65)
        self.pdf.set_font('Helvetica', 'B', 18)
        self.pdf.set_text_color(30, 41, 59)
        self.pdf.cell(30, 10, f"Grade: {self._clean_text(result.grade)}", 0, 0)
        
        self.pdf.ln(30)

    def _render_metrics_table(self, result: MatchResult):
        """Render component scores"""
        metrics = [
            ("Semantic Relevance (Context)", f"{result.semantic_score}%"),
            ("Technical Skills Match", f"{result.skill_score}%"),
            ("Keyword Optimization (ATS)", f"{result.keyword_score}%")
        ]
        
        self.pdf.set_font('Helvetica', '', 11)
        for label, value in metrics:
            self.pdf.set_fill_color(255, 255, 255)
            self.pdf.cell(140, 10, label, 1, 0, 'L', 1)
            self.pdf.set_font('Helvetica', 'B', 11)
            self.pdf.cell(50, 10, value, 1, 1, 'C', 1)
            self.pdf.set_font('Helvetica', '', 11)

    def _render_skills_analysis(self, result: MatchResult):
        """Render matched vs missing skills"""
        # Missing Skills (Red)
        self.pdf.set_font('Helvetica', 'B', 11)
        self.pdf.set_text_color(220, 38, 38)
        self.pdf.cell(0, 8, f"Missing Skills ({len(result.missing_skills)})", 0, 1)
        
        self.pdf.set_font('Helvetica', '', 10)
        self.pdf.set_text_color(51, 65, 85)
        if result.missing_skills:
            # Clean each skill
            clean_skills = [self._clean_text(s) for s in result.missing_skills]
            missing_str = ", ".join(clean_skills[:15])
            if len(result.missing_skills) > 15:
                missing_str += "..."
            self.pdf.multi_cell(0, 6, missing_str)
        else:
            self.pdf.multi_cell(0, 6, "None! Your profile covers all key requirements.")
            
        self.pdf.ln(5)
        
        # Matched Skills (Green)
        self.pdf.set_font('Helvetica', 'B', 11)
        self.pdf.set_text_color(22, 163, 74)
        self.pdf.cell(0, 8, f"Matched Skills ({len(result.matched_skills)})", 0, 1)
        
        self.pdf.set_font('Helvetica', '', 10)
        self.pdf.set_text_color(51, 65, 85)
        if result.matched_skills:
            # Clean each skill
            clean_skills = [self._clean_text(s) for s in result.matched_skills]
            matched_str = ", ".join(clean_skills[:20])
            self.pdf.multi_cell(0, 6, matched_str)
        else:
            self.pdf.multi_cell(0, 6, "No direct skill matches found.")

    def _render_action_plan(self, recommendations: List[str]):
        """Render recommendations"""
        for rec in recommendations:
            clean_rec = self._clean_text(rec)
            
            # Simple bullet point style
            # Use ASCII dash instead of bullet point to ensure compatibility
            self.pdf.set_font('Helvetica', 'B', 14)
            self.pdf.set_text_color(79, 70, 229)
            self.pdf.cell(10, 10, "-", 0, 0)
            
            self.pdf.set_font('Helvetica', '', 11)
            self.pdf.set_text_color(51, 65, 85)
            self.pdf.multi_cell(0, 10, clean_rec)
            self.pdf.ln(2)

    def _get_score_color(self, score: float):
        """Return RGB color tuple based on score"""
        if score >= 80:
            return (22, 163, 74)   # Green
        elif score >= 60:
            return (234, 88, 12)   # Orange
        else:
            return (220, 38, 38)   # Red
